USE imasur_estadisticas;

INSERT INTO especialidades (id_especialidad, nombre, grupo_profesional) VALUES
(1, 'Cardiología', 'Doctor'),
(2, 'Cirugía Cardiovascular', 'Doctor'),
(3, 'Cirugía Vascular Periférico', 'Doctor'),
(4, 'Traumatología', 'Doctor'),
(5, 'Cirugía de Columna', 'Doctor'),
(6, 'Cirugía de Mano', 'Doctor'),
(7, 'Fisiatría', 'Doctor'),
(8, 'Cirugía General', 'Doctor'),
(9, 'Cirugía Plástica', 'Doctor'),
(10, 'Foniatría', 'Doctor'),
(11, 'Gastroenterología', 'Doctor'),
(12, 'Geriatría', 'Doctor'),
(13, 'Ginecología', 'Doctor'),
(14, 'Hematología', 'Doctor'),
(15, 'Medicina Familiar y Ocupacional', 'Doctor'),
(16, 'Terapia Ocupacional', 'Licenciado'),
(17, 'Reumatología', 'Doctor'),
(18, 'Urología', 'Doctor'),
(19, 'Nutrición', 'Licenciado'),
(20, 'Medicina Interna', 'Doctor'),
(21, 'Nefrología', 'Doctor'),
(22, 'Neumonología', 'Doctor'),
(23, 'Neurocirugía', 'Doctor'),
(24, 'Oftalmología', 'Doctor'),
(25, 'Oncología y Mastología', 'Doctor'),
(26, 'Psicología', 'Licenciado'),
(27, 'Psiquiatría', 'Doctor'),
(28, 'Pediatría', 'Doctor'),
(29, 'Cirugía Pediátrica', 'Doctor'),
(30, 'Infectología Pediátrica', 'Doctor'),
(31, 'Nefrología Pediátrica', 'Doctor'),
(32, 'Gastroenterología Pediátrica', 'Doctor'),
(33, 'Neumonología Pediátrica', 'Doctor'),
(34, 'Oncología Pediátrica', 'Doctor'),
(35, 'Ecografía', 'Doctor');

INSERT INTO medicos (nombre_medico, id_especialidad) VALUES
('Mariana Poyer', 1),
('Henry Brito', 1),
('Yonde Kafruni', 2),
('Marlene Rivero', 3),
('Andreina Salmerón', 4),
('Bairon Lovera', 5),
('Daniel Rangel', 6),
('Carlos Golindano', 6),
('Paola López', 7),
('Lashna Hernández', 8),
('Enrique Marín', 8),
('Hernán Malavé', 8),
('Ivana Giménez', 8),
('Felx Mijares', 8),
('Gustavo Gómez', 9),
('Madelbra Villarroel', 9),
('Judas Tadeo Chacón', 10),
('Elisa Castro', 11),
('Rosibel Villegas', 12),
('Vilmania García', 13),
('Stephanie Gómez', 13),
('Ismaris Ortiz', 13),
('Luis Bracamonte', 13),
('Mario González', 14),
('Roxana Díaz', 15),
('Yubetzi Peña', 16),
('Ana Franchi', 17),
('Wilmer Fermín', 18),
('Rumy Cañas', 19),
('Marylena Rodríguez', 20),
('Mylene Martínez', 20),
('Luis Martínez', 20),
('Tibisay Pacheco', 20),
('Susmary Caraballo', 20),
('Mariosca Cumana', 21),
('Migdalys Rojas', 21),
('Shirley Alcántara', 22),
('Lorimar Solórzano', 23),
('Anabel Martínez', 23),
('Ana Rodríguez', 24),
('Diana Medina', 24),
('Danny Amatima', 24),
('María Zambrano', 24),
('Evelin Chacón', 24),
('Ysmael Vegas', 25),
('María Alvarado', 26),
('Ramón Bucarito', 27),
('Mercy Hernández', 28),
('Petra Cusatti', 28),
('José Zerpa', 28),
('Jessimar Torres', 28),
('Juan Borboa', 28),
('Gladinys Núñez', 28),
('Rafael Merchán', 29),
('Carmen Hernández', 29),
('Vanessa Vega', 29),
('María Meza', 29),
('Juan Borboa', 30),
('Yorki Solórzano', 31),
('Ricnia Vizcaíno', 31),
('María Artis', 32),
('José Gregorio Martínez', 33),
('Filomena Mofchella', 34),
('Yanira Urbina', 35);